### ISSUE TITLE
address book support

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#102]
- [x] [support an address book in the backend account](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/100);
- [x] [use address book (address -> description) to label addresses in the app that are otherwise unknown](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/101)
- More Frontend:
   - [x] Be able to display address book in a page and:
      - [x] add a contact
      - [x] modify a contact
      - [x] delete a contact
    - [x] [address book usage in transfer page](#18)
    - [x] Be able to add an unknown wallet address (e.g. in a transaction list) to your contact book in a  click of a button 
  - [x] [add save recipient checkbox in transfer page](#141)

**Comment by GlenDC** [comment]
Let's start working on this only after we have v0.1.2 ready tomorrow.

**Comment by GlenDC** [comment]
Contact info has:

- name (optional)
- multisig or singlesig (separate data types as we need to store more info for multisig contacts)
