### ISSUE TITLE
full multisig wallet support in App

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#65]
Prerequisites:
- [x] [create global store of account / wallet balances which will trigger updates on all components](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/49) (frontend);
- [x] [sign + signs-required pages](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/35) (frontend);
   - [x] dependency for signing (and sending again): [provide wallet API to sign raw transaction and send if possible](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/51) (backend);

Extra:
- [x] [cached wallet support](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/77) (backend);
- [x] [use cached wallet API in frontend code](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/78) (frontend);

Tasks:
- [x] [be able to transfer money to a multisig wallet](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/56) (frontend);
- [x] [be able to detect multisig wallets via account balance object](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/50) (backend);
- [x] [save labeled multisig wallets in account serialization](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/63) (backend);
- [x] [multisig wallet page](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/62) (frontend);
- [x] [show multisig wallets on account page](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/64) (frontend);

**Comment by GlenDC** [comment]
Now that we have a working desktop application, this story is the top priority, as it was the reason we started this project (and did so very fast indeed).

TFTech will be the first user of this feature, as they need it to manage the company MultiSig wallet.

**Comment by GlenDC** [comment]
Frontend will be done by you @DylanVerstraete, will make sure that you have all the backend stuff :)

**Comment by GlenDC** [comment]
Example of API to sign transactions:

```javascript
account.wallet.transaction_sign('{"version":1,"data":{...}}').then(result => {
    result.signed // True if we added at least one signature, False otherwise
    result.submitted // True if the transaction was submitted to the explorer node's transaction pool (== sent)
    result.transaction // Modified transaction, use `result.transaction.json()` to get an object that can be stringified using JSON.stringify
})
```

**Comment by GlenDC** [comment]
Works.
